# Cloud Build CI/CD — builds and deploys all services to Cloud Run
# Triggered on push to main branch
#
# Prerequisites:
#   1. Create JWT secret: gcloud secrets create jwt-secret --data-file=- <<< "your-secret-here"
#   2. Grant Cloud Build access: gcloud secrets add-iam-policy-binding jwt-secret \
#        --member="serviceAccount:$(gcloud projects describe prodigee-488119 --format='value(projectNumber)')@cloudbuild.gserviceaccount.com" \
#        --role="roles/secretmanager.secretAccessor"
#   3. Grant Cloud Run invoker for service-to-service auth

substitutions:
  _REGION: us-east1
  _PROJECT_ID: prodigee-488119
  _REPO: prodigee

steps:
  # --- Build all service images in parallel ---

  - id: build-gateway
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/gateway:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/gateway:latest
      - ./services/gateway
    waitFor: ["-"]

  - id: build-auth
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/auth:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/auth:latest
      - ./services/auth
    waitFor: ["-"]

  - id: build-learning-engine
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/learning-engine:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/learning-engine:latest
      - ./services/learning-engine
    waitFor: ["-"]

  - id: build-analytics
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/analytics:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/analytics:latest
      - ./services/analytics
    waitFor: ["-"]

  - id: build-ar-vr
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/ar-vr:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/ar-vr:latest
      - ./services/ar-vr
    waitFor: ["-"]

  # --- Push all images ---

  - id: push-images
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker push ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/gateway:$COMMIT_SHA
        docker push ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/gateway:latest
        docker push ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/auth:$COMMIT_SHA
        docker push ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/auth:latest
        docker push ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/learning-engine:$COMMIT_SHA
        docker push ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/learning-engine:latest
        docker push ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/analytics:$COMMIT_SHA
        docker push ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/analytics:latest
        docker push ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/ar-vr:$COMMIT_SHA
        docker push ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/ar-vr:latest
    waitFor:
      - build-gateway
      - build-auth
      - build-learning-engine
      - build-analytics
      - build-ar-vr

  # --- Deploy Firestore security rules ---
  # NOTE: Firestore rules are deployed manually for now:
  #   npx firebase-tools deploy --only firestore:rules --project prodigee-488119
  # TODO: Restore automated deploy once Firebase CLI auth is configured in Cloud Build

  # --- Deploy to Cloud Run ---
  # Gateway: public-facing, routes to internal services
  # Backend services: allow-unauthenticated (JWT validated at app layer)
  # TODO: Upgrade to --no-allow-unauthenticated + identity token injection in gateway
  # JWT secret mounted from Secret Manager for all JWT-aware services

  - id: deploy-gateway
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        echo "Discovering backend service URLs..."
        AUTH_URL=$$(gcloud run services describe prodigee-auth --region=${_REGION} --format='value(status.url)')
        LEARNING_URL=$$(gcloud run services describe prodigee-learning-engine --region=${_REGION} --format='value(status.url)')
        ANALYTICS_URL=$$(gcloud run services describe prodigee-analytics --region=${_REGION} --format='value(status.url)')
        ARVR_URL=$$(gcloud run services describe prodigee-ar-vr --region=${_REGION} --format='value(status.url)')
        echo "Auth: $${AUTH_URL}"
        echo "Learning: $${LEARNING_URL}"
        echo "Analytics: $${ANALYTICS_URL}"
        echo "AR/VR: $${ARVR_URL}"
        gcloud run deploy prodigee-gateway \
          --image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/gateway:$COMMIT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=256Mi \
          --cpu=1 \
          --min-instances=0 \
          --max-instances=10 \
          --set-env-vars="GATEWAY_ENVIRONMENT=production,GATEWAY_AUTH_SERVICE_URL=$${AUTH_URL},GATEWAY_LEARNING_SERVICE_URL=$${LEARNING_URL},GATEWAY_ANALYTICS_SERVICE_URL=$${ANALYTICS_URL},GATEWAY_AR_VR_SERVICE_URL=$${ARVR_URL}"
    waitFor: [deploy-auth, deploy-learning-engine, deploy-analytics, deploy-ar-vr]

  - id: deploy-auth
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - prodigee-auth
      - --image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/auth:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=256Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=5
      - --set-env-vars=AUTH_ENVIRONMENT=production,AUTH_PROJECT_ID=${_PROJECT_ID}
      - --set-secrets=AUTH_JWT_SECRET=jwt-secret:latest
    waitFor: [push-images]

  - id: deploy-learning-engine
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - prodigee-learning-engine
      - --image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/learning-engine:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=5
      - --set-env-vars=LEARNING_ENVIRONMENT=production,LEARNING_PROJECT_ID=${_PROJECT_ID},LEARNING_REGION=${_REGION}
      - --set-secrets=LEARNING_JWT_SECRET=jwt-secret:latest
    waitFor: [push-images]

  - id: deploy-analytics
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - prodigee-analytics
      - --image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/analytics:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=256Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=5
      - --set-env-vars=ANALYTICS_ENVIRONMENT=production,ANALYTICS_PROJECT_ID=${_PROJECT_ID}
      - --set-secrets=ANALYTICS_JWT_SECRET=jwt-secret:latest
    waitFor: [push-images]

  - id: deploy-ar-vr
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - prodigee-ar-vr
      - --image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/ar-vr:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=256Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
      - --set-env-vars=ARVR_ENVIRONMENT=production
    waitFor: [push-images]

options:
  logging: CLOUD_LOGGING_ONLY
